apiVersion: vernal.dev/v1alpha1
kind: Application
metadata:
  labels:
    app.kubernetes.io/name: application
    app.kubernetes.io/instance: application-sample
    app.kubernetes.io/part-of: vernal-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: vernal-operator
  name: application-sample
spec:
  repo:
    url: https://github.com/vernaldev/test
    revision: main
    path: .
