apiVersion: vernal.dev/v1alpha1
kind: Application
metadata:
  name: test
spec:
  owner: dennis
  repo:
    url: https://github.com/vernaldev/test
    revision: main
    path: vernal.yaml
  components:
  - name: whoami
    image: traefik/whoami:latest
    containerPort: 80
  - name: httpbin
    image: kennethreitz/httpbin:latest
    containerPort: 80
